#
# Module manifest for module 'Microsoft365DSC'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2025-10-02

@{

  # Script module or binary module file associated with this manifest.
  # RootModule = ''

  # Version number of this module.
  ModuleVersion     = '1.25.1001.1'

  # Supported PSEditions
  # CompatiblePSEditions = @()

  # ID used to uniquely identify this module
  GUID              = '39f599a6-d212-4480-83b3-a8ea2124d8cf'

  # Author of this module
  Author            = 'Microsoft Corporation'

  # Company or vendor of this module
  CompanyName       = 'Microsoft Corporation'

  # Copyright statement for this module
  Copyright         = '(c) 2025 Microsoft Corporation. All rights reserved.'

  # Description of the functionality provided by this module
  Description       = 'This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.'

  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '5.1'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # CLRVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
  RequiredModules   = @()

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  ScriptsToProcess = @(
    'Update-MaximumFunctionCount.ps1'
  )

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  NestedModules     = @(
    'Modules/M365DSCAgent.psm1',
    'Modules/M365DSCDocGenerator.psm1',
    'Modules/M365DSCErrorHandler.psm1',
    'Modules/M365DSCLogEngine.psm1',
    'Modules/M365DSCPermissions.psm1',
    'Modules/M365DSCReport.psm1',
    'Modules/M365DSCReverse.psm1',
    'Modules/M365DSCStubsUtility.psm1',
    'Modules/M365DSCTelemetryEngine.psm1',
    'Modules/M365DSCUtil.psm1',
    'Modules/M365DSCDRGUtil.psm1',
    'Modules/M365DSCIntuneSettingsCatalogUtil.psm1',
    'Modules/EncodingHelpers/M365DSCEmojis.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureDevOPSHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCDefenderHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCFabricHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCLicensingHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCPowerPlatformRESTHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCServicesHubHelper.psm1',
    'Modules/M365DSCConfigurationHelper.psm1'
  )

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  #FunctionsToExport = @()

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport   = @(
    'Assert-M365DSCBlueprint',
    'Compare-M365DSCConfigurations',
    'Confirm-M365DSCDependencies',
    'Export-M365DSCConfiguration',
    'Export-M365DSCDiagnosticData',
    'Get-M365DSCNotificationEndPointRegistration',
    'Get-M365DSCEvaluationRulesForConfiguration',
    'Join-M365DSCConfiguration',
    'New-M365DSCDeltaReport',
    'New-M365DSCNotificationEndPointRegistration',
    'New-M365DSCReportFromConfiguration',
    'New-M365DSCStubFiles',
    'Remove-M365DSCNotificationEndPointRegistration',
    'Set-M365DSCAgentCertificateConfiguration',
    'Test-M365DSCAgent',
    'Test-M365DSCDependenciesForNewVersions',
    'Test-M365DSCModuleValidity',
    'Uninstall-M365DSCOutdatedDependencies',
    'Update-M365DSCAllowedGraphScopes',
    'Update-M365DSCAzureAdApplication',
    'Update-M365DSCDependencies',
    'Update-M365DSCModule',
    'Update-M365DSCResourceDocumentationPage',
    'Update-M365DSCResourcesSettingsJSON'
  )

  # Variables to export from this module
  # VariablesToExport = @()

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport   = @()

  # List of all modules packaged with this module
  # ModuleList = @()

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{

    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      Tags         = 'DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource', 'Microsoft365'

      # A URL to the license for this module.
      LicenseUri   = 'https://github.com/Microsoft/Microsoft365DSC/blob/master/LICENSE'

      # A URL to the main website for this project.
      ProjectUri   = 'https://github.com/Microsoft/Microsoft365DSC'

      # A URL to an icon representing this module.
      IconUri      = 'https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Images/Logo.png?raw=true'

      # ReleaseNotes of this module
      ReleaseNotes = '* AADAccessReviewDefinition
  * [BREAKING CHANGE] Removed ID as the key and made DisplayName the new key.
* AADAdministrativeUnit
  * Reduced export time by 20%.
* AADAgreement
  * Fixed creation and update issues by calling the APIs directly.
* AADApplication
  * [BREAKING CHANGE] Removed deprecated parameters `AvailableToOtherTenants`
    and `RequireClientServicePrincipal`.
* AADAppManagementPolicy
  * Updated `RestrictForAppsCreatedAfterDateTime` to "o" format.
* AADAuthenticationMethodPolicy
  * [BREAKING CHANGE] Removed deprecated parameter `PolicyMigrationState`.
* AADAuthenticationMethodPolicyAuthenticator
  * [BREAKING CHANGE] Removed deprecated parameter `NumberMatchingRequiredState`.
* AADConditionalAccessPolicy
  * Fix case evaluation when creating instances or updating properties.
* AADCrossTenantIdentitySyncPolicyPartner
  * Initial release.
* AADCustomSecurityAttributeDefinition
  * [BREAKING CHANGE] Restricted accepted values for `Status` to `Available` and
    `Deprecated`.
* AADDomain
  * Fixed an issue where updating an existing instance failed due to the
    isVerified parameter.
* AADEnrichedAuditLogs
  * [BREAKING CHANGE] Removed deprecated resource.
* AADGroup
  * Fixed multi-tenant Service Principal support for owners and members.
    FIXES [#6498](https://github.com/microsoft/Microsoft365DSC/issues/6498)
  * Fixed an issue where the `SkuId` could contain NBSP characters.
    FIXES [#6476](https://github.com/microsoft/Microsoft365DSC/issues/6476)
  * Fixed an issue where GroupAsMembers not being added during initial group creation.
    FIXES [#6489](https://github.com/microsoft/Microsoft365DSC/issues/6489)
  * Fixed an issue where not all members were exported.
    FIXES [#6545](https://github.com/microsoft/Microsoft365DSC/issues/6545)
* AADGroupEligiblitySchedule
  * Aligned date time format for `Expiration.EndDateTime` with `Expiration.StartDateTime`.
  * [BREAKING CHANGE] Update AADGroupEligiblitySchedule align with
    AADRoleEligibilityScheduleRequest to allow User (UPN), Group (Group Name) as
    Principal
  * Fixed issue where AADGroupEligiblitySchedule didn`t correctly work with
    member and owner assignment types
* EXOAtpPolicyForO365
  * [BREAKING CHANGE] Removed `Ensure` property.
* EXOCalendarProcessing
  * Added caching for export.
* EXOClientAccessRule
  * [BREAKING CHANGE] Removed resource.
* EXOFocusedInbox
  * [BREAKING CHANGE] Removed deprecated parameter `FocusedInboxOnLastUpdateTime`.
* EXOGroupSettings
  * Fixed an issue with the retrieval by DisplayName and duplicate Id property
    on update.
  * [BREAKING CHANGE] Renamed the UnifiedGroupWelcomeMessageEnabled parameter to
    WelcomeMessageEnabled.
* EXOIntraOrganizationConnector
  * Fix logic to allow empty string for TargetSharingEpr.
* EXOHostedContentFilterPolicy
  * [BREAKING CHANGE] Remove deprecated properties `DownloadLink`, `EnableEndUserSpamNotifications`,
    `EndUserSpamNotificationCustomSubject`, `EndUserSpamNotificationFrequency`
    and `EndUserSpamNotificationLanguage`.
    FIXES [#4958](https://github.com/microsoft/Microsoft365DSC/issues/4958)
* EXOMailboxAutoReplyConfiguration
  * Added conditional user lookup.
* EXOMailboxCalendarFolder
  * Added conditional user lookup.
* EXOMailContact
  * Added caching for export.
* EXOMailboxPermission
  * Added additional caching for export.
* EXOMailboxSettings
  * Added caching for export.
* EXOMobileDeviceMailboxPolicy
  * [BREAKING CHANGE] Updated properties `MinPasswordComplexCharacters` and
    `PasswordHistory` to integer types.
    FIXES [#6022](https://github.com/microsoft/Microsoft365DSC/issues/6022)
* EXORecipientPermission
  * Added additional caching for export.
* EXOSafeAttachmentPolicy
  * [BREAKING CHANGE] Removed deprecated parameter `ActionOnError`.
* EXOTransportRule
  * [BREAKING CHANGE] Removed deprecated parameters `ExceptIfHasSenderOverride`,
    `MessageContainsDataClassifications`,
    `ExceptIfMessageContainsDataClassifications`, `HasSenderOverride`,
    `NotifySender`, `ApplyOME` and `RemoveOME`.
* IntuneAccountProtectionPolicy
  * [BREAKING CHANGE] Removed deprecated resource.
* IntuneAccountProtectionLocalUserGroupMembershipPolicy
  * [BREAKING CHANGE] Renamed properties to match their Settings Catalog counterpart.
    FIXES [#6342](https://github.com/microsoft/Microsoft365DSC/issues/6432)
* IntuneAppCategory
  * Added missing authentication properties in examples.
* IntuneAppConfigurationPolicy
  * Fixed an issue with MOF instance parsing.
    FIXES [#6520](https://github.com/microsoft/Microsoft365DSC/issues/6520)
* IntuneAppControlForBusinessPolicyWindows10
  * Initial release.
    FIXES [#4761](https://github.com/microsoft/Microsoft365DSC/issues/4761)
* IntuneAppProtectionPolicyAndroid
  * [BREAKING CHANGE] Combined `ExcludedGroups` with `Assignments`, updated
    time parameters to ISO8601 format, removed `IsAssigned` property.
    FIXES [#5968](https://github.com/microsoft/Microsoft365DSC/issues/5968)
    FIXES [#5808](https://github.com/microsoft/Microsoft365DSC/issues/5808)
    FIXES [#5675](https://github.com/microsoft/Microsoft365DSC/issues/5675)
* IntuneAppConfigurationPolicy
  * Fixed an issue with MOF instance parsing.
    FIXES [#6520](https://github.com/microsoft/Microsoft365DSC/issues/6520)
* IntuneASRRulesPolicyWindows10
  * [BREAKING CHANGE] Removed resource. It was replaced with `IntuneSettingCatalogASRRulesPolicyWindows10`.
* IntuneDeviceCleanupRule
  * [BREAKING CHANGE] Removed resource. It was replaced with `IntuneDeviceCleanupRuleV2`.
* IntuneDeviceCompliancePolicyAndroid
  * [BREAKING CHANGE] Removed resource because the configuration type is not
    supported anymore.
* IntuneDeviceConfigurationPolicyAndroidDeviceAdministrator
  * [BREAKING CHANGE] Removed resource because the configuration type is not
    supported anymore.
* IntuneDeviceRemediation
  * [BREAKING CHANGE] Made Id optional and enabled creation of remediation
    scripts using DisplayName only.
    FIXES [#6445](https://github.com/microsoft/Microsoft365DSC/issues/6445)
* IntuneEpmElevationRulesPolicyWindows10
  * Initial release.
* IntuneEpmElevationSettingsPolicyWindows10
  * Initial release.
* IntuneMobileAppsMacOSLobApp
  * Added filter capability.
* IntuneMobileAppsMicrosoftStoreAppWindows10
  * Initial release.
* IntuneMobileAppsStoreApp
  * Added support for `assignmentSettings` to the assignments.
* IntuneMobileAppsWebLink
  * Fixed an issue where filtering was applied after fetching all apps.
* IntuneMobileAppsWindowsOfficeSuiteApp
  * Added filter capability.
  * Fixed the version in the MOF definition.
* IntuneRoleAssignment
  * Fixed an issue where deleted groups would throw an error during export.
* IntuneTrustedRootCertificateAndroidEnterprise
  * [BREAKING CHANGE] Removed resource because the configuration type is not
    supported anymore.
* IntuneUserSettingsPolicyWindows365
  * Initial release.
* IntuneVPNConfigurationPolicyAndroidEnterprise
  * [BREAKING CHANGE] Removed resource because the configuration type is not
    supported anymore.
* IntuneWifiConfigurationPolicyAndroidDeviceAdministrator
  * [BREAKING CHANGE] Removed resource because the configuration type is not
    supported anymore.
* IntuneWifiConfigurationPolicyAndroidForWork
  * [BREAKING CHANGE] Removed resource because it`s not supported anymore.
    Instead, use the `IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile`
    resource.
* O365AdminAuditLogConfig
  * [BREAKING CHANGE] Removed `Ensure` parameter because it is a single instance
    object.
* O365OrgSettings
  * [BREAKING CHANGE] Removed deprecated parameter `MicrosoftVivaBriefingEmail`.
* ODSettings
  * [BREAKING CHANGE] Removed deprecated parameter `NotifyOwnersWhenInvitationsAccepted`.
* SPOPropertyBag
  * Reduced export time by 85%.
* SPOSharingSettings
  * [BREAKING CHANGE] Removed deprecated parameter `RequireAcceptingAccountMatchInvitedAccount`.
* SPOSite
  * Added additional caching.
* SPOTenantSettings
  * [BREAKING CHANGE] Removed deprecated parameter `UserVoiceForFeedbackEnabled`.
  * Fixed the retrieval and update of the OneDriveSharingCapability parameter.
* TeamsChannel
  * Reduced export time by up to 75%.
* TeamsChannelTab
  * Reduced export time by up to 85%.
* TeamsFederationConfiguration
  * [BREAKING CHANGE] Removed deprecated parameter `AllowPublicUsers`.
* TeamsMeetingPolicy
  * [BREAKING CHANGE] Removed deprecated parameter `ForceStreamingAttendeeMode`.
* TeamsShiftsPolicy
  * [BREAKING CHANGE] Removed deprecated parameter `EnableShiftPresence`.
* TeamsTenantDialPlan
  * [BREAKING CHANGE] Removed deprecated parameter `OptimizeDeviceDialing` and `ExternalAccessPrefix`.
* MISC
  * Added ordering to hashtables.
  * [BREAKING CHANGE] Changed multiple property values and types in Intune resources.
    Refer to the
    breaking change blog post for more information about the affected resources.
  * Added performance improvements to speed up resource processing.
  * Code cleanup across all Intune resources.
  * Code cleanup across all O365, OD and SPO resources.
  * Code cleanup across all Planner, PP and SC resources.
  * Code cleanup across all Sentinel, SH and Teams resources.
  * Code cleanup across all M365DSC modules.
  * Fixed typo in `ManagedIdentity` property across all resources.
  * Improved module import speed by up to 60%.
  * Reduced repeated logins during export of SPO and Teams resources.
  * Removed unnecessary type casting across all resources.
  * Streamlined test cases.
  * Updated most resource testing to use the new comparison function.
  * Updated required modules for Intune resources doing assignments to groups.
  * [BREAKING CHANGE] Removed `SupportsScopeTags` property from all resources
    because it`s read-only.
  * Updated all resource settings files to include a `configuration` or `data` mode.
* M365DSCDRGUtil
  * Changed the way how Settings Catalog properties are exported.
  * Fixed an issue where a null drift would throw an exception.
  * Fixed an issue where group filtering would not find the specified groups.
  * Fixed an issue where 0 requests passed to `Invoke-M365DSCGraphBatchRequests`
    would fail.
    FIXES [#6521](https://github.com/microsoft/Microsoft365DSC/issues/6521)
  * Fixed an issue with applying Intune Settings Catalog policies.
* M365DSCUtil
  * Added parameter `-Parallel` to `Export-M365DSCConfiguration`.
  * Renamed function `Get-M365DSCWorkloadsListFromResourceNames` to `Get-M365DSCConnectedWorkloadList`.
  * Added function `Get-M365DSCWorkloadForResource` to look up the workload of
    a resource.
  * Added function `Get-M365DSCResourcesByExportMode` to determine which
    resources belong to an export mode.
* DEPENDENCIES
  * Updated MSCloudLoginAssistant to version 1.1.51.'

      # Flag to indicate whether the module requires explicit user acceptance for install/update
      # RequireLicenseAcceptance = $false

      # External dependent modules of this module
      # ExternalModuleDependencies = @()

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''
}
