#
# Module manifest for module 'Microsoft365DSC'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2025-09-04

@{

  # Script module or binary module file associated with this manifest.
  # RootModule = ''

  # Version number of this module.
  ModuleVersion     = '1.25.903.1'

  # Supported PSEditions
  # CompatiblePSEditions = @()

  # ID used to uniquely identify this module
  GUID              = '39f599a6-d212-4480-83b3-a8ea2124d8cf'

  # Author of this module
  Author            = 'Microsoft Corporation'

  # Company or vendor of this module
  CompanyName       = 'Microsoft Corporation'

  # Copyright statement for this module
  Copyright         = '(c) 2025 Microsoft Corporation. All rights reserved.'

  # Description of the functionality provided by this module
  Description       = 'This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.'

  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '5.1'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # CLRVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
  RequiredModules   = @()

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  ScriptsToProcess = @(
    'Update-MaximumFunctionCount.ps1'
  )

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  NestedModules     = @(
    'Modules/M365DSCAgent.psm1',
    'Modules/M365DSCDocGenerator.psm1',
    'Modules/M365DSCErrorHandler.psm1',
    'Modules/M365DSCLogEngine.psm1',
    'Modules/M365DSCPermissions.psm1',
    'Modules/M365DSCReport.psm1',
    'Modules/M365DSCReverse.psm1',
    'Modules/M365DSCStubsUtility.psm1',
    'Modules/M365DSCTelemetryEngine.psm1',
    'Modules/M365DSCUtil.psm1',
    'Modules/M365DSCDRGUtil.psm1',
    'Modules/M365DSCIntuneSettingsCatalogUtil.psm1',
    'Modules/EncodingHelpers/M365DSCEmojis.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureDevOPSHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCDefenderHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCFabricHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCLicensingHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCPowerPlatformRESTHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCServicesHubHelper.psm1',
    'Modules/M365DSCConfigurationHelper.psm1'
  )

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  #FunctionsToExport = @()

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport   = @(
    'Assert-M365DSCBlueprint',
    'Compare-M365DSCConfigurations',
    'Confirm-M365DSCDependencies',
    'Export-M365DSCConfiguration',
    'Export-M365DSCDiagnosticData',
    'Get-M365DSCNotificationEndPointRegistration',
    'Get-M365DSCEvaluationRulesForConfiguration',
    'Join-M365DSCConfiguration',
    'New-M365DSCDeltaReport',
    'New-M365DSCNotificationEndPointRegistration',
    'New-M365DSCReportFromConfiguration',
    'New-M365DSCStubFiles',
    'Remove-M365DSCNotificationEndPointRegistration',
    'Set-M365DSCAgentCertificateConfiguration',
    'Test-M365DSCAgent',
    'Test-M365DSCDependenciesForNewVersions',
    'Test-M365DSCModuleValidity',
    'Uninstall-M365DSCOutdatedDependencies',
    'Update-M365DSCAllowedGraphScopes',
    'Update-M365DSCAzureAdApplication',
    'Update-M365DSCDependencies',
    'Update-M365DSCModule',
    'Update-M365DSCResourceDocumentationPage',
    'Update-M365DSCResourcesSettingsJSON'
  )

  # Variables to export from this module
  # VariablesToExport = @()

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport   = @()

  # List of all modules packaged with this module
  # ModuleList = @()

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{

    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      Tags         = 'DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource', 'Microsoft365'

      # A URL to the license for this module.
      LicenseUri   = 'https://github.com/Microsoft/Microsoft365DSC/blob/master/LICENSE'

      # A URL to the main website for this project.
      ProjectUri   = 'https://github.com/Microsoft/Microsoft365DSC'

      # A URL to an icon representing this module.
      IconUri      = 'https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Images/Logo.png?raw=true'

      # ReleaseNotes of this module
      ReleaseNotes = '* AADAccessReviewDefinition
  * Added properties `FallbackReviewers` and `Reviewers`.
    FIXES [#5674](https://github.com/microsoft/Microsoft365DSC/issues/5674)
* AADApplication
  * Fixed an issue where owners would not be set during creation.
    FIXES [#6238](https://github.com/microsoft/Microsoft365DSC/issues/6238)
* AADEntitlementManagementAccessPackageAssignmentPolicy
  * Added support for Groups as well as single users.
    FIXES [#6257](https://github.com/microsoft/Microsoft365DSC/issues/6257)
* AADAuthenticationStrengthPolicy
  * Filter out built-in policies because they cannot be modified.
* AADEntitlementManagementRoleAssignment
  * Added functionality to export groups and service principals.
    Fixed an issue where the export of `Connected organization administrator` assignments would fail.
    FIXES [#5620](https://github.com/microsoft/Microsoft365DSC/issues/5620)
    FIXES [#5618](https://github.com/microsoft/Microsoft365DSC/issues/5618)
* AADServicePrincipal
  * Fixed an issue where assigning members to a Service Principal would throw an error when
    more than one member was assigned.
* ADOPermissionGroupSettings
  * Reduced export time by 90%.
* IntuneAntivirusPolicyWindows10ConfigMgr
  * Initial release.
* IntuneAntivirusPolicySecurityExperienceWindows10ConfigMgr
  * Initial release.
    FIXES [#4229](https://github.com/microsoft/Microsoft365DSC/issues/4229)
* IntuneDeviceComplianceNotificationMessageTemplate
  * Initial release.
* IntuneDeviceComplianceScriptLinux
  * Initial release.
* IntuneDeviceManagementComplianceSettings
  * Updated `DeviceComplianceCheckinThresholdDays` to use the default value of 30 days
    if the backend reports 0 as the value.
    FIXES [#6450](https://github.com/microsoft/Microsoft365DSC/issues/6450)
  * Restricted possible values for `DeviceComplianceCheckinThresholdDays` from 1 to 120.
* IntuneMobileAppsWin32AppWindows10
  * Bump CIM instance version to fix invalid property name.
* IntuneMobileAppsWindowsOfficeSuiteApp
  * Fixes problem with OfficeConfigurationXml.Changed from type byte to type
    String as APi expect a string that is encoded in Base64 format.
* IntuneSecurityBaselineMicrosoftEdge
  * Fixed an issue where the latest policy version was not exported.
    FIXES [#6415](https://github.com/microsoft/Microsoft365DSC/issues/6415)
* IntuneWindowsUpdateForBusinessHotpatchProfileWindows10
  * Initial release.
    FIXES [#6368](https://github.com/microsoft/Microsoft365DSC/issues/6368)
* PPPowerAppsEnvironment
  * Fixed a variable naming conflict for environments provisioned through Microsoft Teams.
    FIXES [#6404](https://github.com/microsoft/Microsoft365DSC/issues/6404)
* SCInsiderRiskPolicy
  * Fixed an issue where an empty `EnableTeam` value would throw during Get operation.
* TeamsCallingPolicy
  * Added 12 new supported properties.
* TeamsMeetingBroadcastConfiguration
  * Fixes an issue where the SdnAPIToken wasn`t exported as a string.
* TeamsMessagingPolicy
  * Added support for 12 new properties.
* TeamsTeam
  * Fixed an issue where an invalid search query was invoked.
    FIXES [#5937](https://github.com/microsoft/Microsoft365DSC/issues/5937)
* MISC
  * Code cleanup across all AAD, ADO and Azure resources.
  * Fixing issues connection SPO to sovereign clouds.
  * Fixed an issue across Intune resources using the Settings Catalog which
    were not correctly setting their `RoleScopeTagIds`.
    FIXES [#6434](https://github.com/microsoft/Microsoft365DSC/issues/6434)
  * Fixed issues when connecting SPO to sovereign clouds.
  * Updated settings and formatting of method names across all resources.
  * Updated documentation for configuring workload authentication.
  * Updated permissions for EXO resources.
    FIXES [#3841](https://github.com/microsoft/Microsoft365DSC/issues/3841)
* DEPENDENCIES
  * Updated ExchangeOnlineManagement to version 3.9.0.
    FIXES [#6106](https://github.com/microsoft/Microsoft365DSC/issues/6106)
  * Include `Az.Security` module for `Defender` workload.
* M365DSCTelemetryEngine
  * Changed logic to retrieve the global telemetry authentication parameters.
* M365DSCUtil
  * Changed logic to provide the global telemetry authentication parameters.
  * Moved sizing of batch requests to `Invoke-M365DSCGraphBatchRequest`.
  * Fixed a comparison issue in `Compare-M365DSCComplexObject`.
    Supersedes [#6196](https://github.com/microsoft/Microsoft365DSC/pull/6196).'

      # Flag to indicate whether the module requires explicit user acceptance for install/update
      # RequireLicenseAcceptance = $false

      # External dependent modules of this module
      # ExternalModuleDependencies = @()

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''
}
